version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - skillvine-api
    
  skillvine-api:
    image: skillvine-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development-build
    ports:
      - "5000:5000"
    container_name: skillvine-api
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NODE_ENV}